add xsync for evm and relay block
jimmy1984xu/TOP-chain pull request #223
Opened 2022-07-08 10:32 UTC by hench-ye

2022-07-08 10:58 UTC, jimmy1984xu commented on src/xtopcom/xtxstore/xtxstoreimpl.h
> +    common::xbool_strategy_t m_txstore_relay_strategy;
why add m_txstore_relay_strategy?

2022-07-08 11:08 UTC, jimmy1984xu commented on src/xtopcom/xblockstore/src/xvunithub.cpp
> +                base::xvchain_t::instance().get_xtxstore()->check_relay_store()) {
relay_block should be unpacked and stored in relay nodes now

2022-07-08 11:11 UTC, jimmy1984xu commented on src/xtopcom/xblockstore/src/xvblockhub.cpp
> +            if (base::xvchain_t::instance().get_xtxstore()->check_relay_store()) {
store relayblock txs  should be provided by txstore and controlled by txstore

2022-07-11 10:34 UTC, jimmy1984xu commented on src/xtopcom/xtxstore/src/xtxstoreimpl.cpp
> +bool xtxstoreimpl::store_relay_txs(base::xvblock_t * block_ptr) {
should do permission control

2022-07-12 02:28 UTC, PaytonWu requested changes

2022-07-12 02:28 UTC, PaytonWu commented on src/libraries/xsync/src/xsync_object.cpp
> +common::xenum_node_type xtop_sync_object::get_table_type(const std::string& table_prefix) const {
1. better to use common::xaccount_base_address_t.
2. common::xaccount_base_address_t makes sure it doesn't contain '@table_id' part.  
3. common::xaccount_address_t may contain '@table_id'. and common::xaccount_address_t has 'base_address()' API to get corresponding common::xaccount_base_address_t data.
4. in xnative_contract_address.h, it defines 'rec_table_address' which is equal to 'sys_contract_beacon_table_block_addr' but in type of common::xaccount_address_t
5. do not use string type anymore.

2022-07-12 02:28 UTC, PaytonWu commented on src/libraries/xsync/src/xsync_object.cpp
> +std::string xtop_sync_object::get_title(common::xenum_node_type type) const {
in xnode_type.h, it declares 'std::string to_presentation_string(xnode_type_t type);' API for getting string presentation of a concrete node type.

2022-07-12 02:28 UTC, PaytonWu commented on src/libraries/xsync/src/xsync_object.cpp
> +        std::map<common::xenum_node_type, std::map<uint32_t, xsync_progress_t>> tables_progress;
replace common::xenum_node_type by common::xnode_type_t

2022-07-12 02:28 UTC, PaytonWu commented on src/libraries/xsync/src/xsync_object.cpp
> +        for (auto it:tables_progress) {
auto const &

2022-07-12 02:28 UTC, PaytonWu commented on src/libraries/xsync/xrole_xips_manager.h
> +    std::vector<common::xnode_address_t> get_relay_list();
const API?

2022-07-12 02:28 UTC, PaytonWu commented on src/xtopcom/xdata/xnative_contract_address.h
>  XINLINE_CONSTEXPR char const * sys_contract_relay_block_addr{"Tb0005@0"};
why we add a 'b' type?

2022-07-12 02:28 UTC, PaytonWu commented on src/xtopcom/xtxstore/src/xtxstoreimpl.cpp
> +bool xtxstoreimpl::check_relay_store() {
const API

2022-07-12 03:05 UTC, PaytonWu commented on src/xtopcom/xdata/xnative_contract_address.h
>  XINLINE_CONSTEXPR char const * sys_contract_relay_block_addr{"Tb0005@0"};
i got the answer

2022-07-12 03:08 UTC, hench-ye commented on src/libraries/xsync/src/xsync_object.cpp
> +std::string xtop_sync_object::get_title(common::xenum_node_type type) const {
not the same

2022-07-12 03:14 UTC, hench-ye commented on src/xtopcom/xdata/xnative_contract_address.h
>  XINLINE_CONSTEXPR char const * sys_contract_relay_block_addr{"Tb0005@0"};
a new type

2022-07-18 11:11 UTC, closed without merging